### ISSUE TITLE
Update RPD Buildings and EVCS Stalls layers

### ISSUE THREAD

**Issue by michaelpnelson** [bcgov/smk-clean-bc#111]

**Comment by michaelpnelson** [comment]
@bethbyoung , just giving you an update on this at the end of my day :) .

I have the EVCS layer looking good in local testing. It looks like, for stall type, the EVCS type was replaced with "Employee/Public", so it looks like this (don't mind the missing base map - I didn't have my Esri API key loaded) ...

<img width="436" alt="Screenshot 2023-03-30 at 4 00 22 PM" src="https://user-images.githubusercontent.com/1911540/228983490-627d0c37-48ce-490b-b451-66b367369ab2.png">

I _am_ having difficulty with the new RPD Buildings layer file - it doesn't show any points at all for me at present. I'm diagnosing the issue but it looks like something might be awry in the file data. If I trim away most of the features in the file I can see points. I should know more soon.

**Comment by bethbyoung** [comment]
Hi Michael,

Thanks for getting to work on this so quickly. I looked at the buildings, and it looks like the projection did not come over correctly. I have attached a revised version. Please let me know if you have any issues with this one.

Thanks,
Beth

**Comment by bethbyoung** [comment]
Hi Michael,

I tried to attach the geoson to the github comment section previously, but it said it didn’t support that file type. I also had the geojson attached in the last email message, so weird you couldn’t see it. I have attached it again, let me know if you still are unable to view it.

Thanks,
Beth

**Comment by michaelpnelson** [comment]
I think that when replying to a notification email from GitHub and including an attachment, the attachment doesn't make it into the GitHub issue.

Could you send a new email directly to me (michael.nelson@gov.bc.ca) with the attachment? Thanks ...

**Comment by michaelpnelson** [comment]
Thanks for the new RPD Buildings layer, @bethbyoung .

I can now see the points. It looks like there are fewer features in the newest version.

I'm also seeing considerable difference between the feature attributes, especially between the first and second attachment you sent. Here's the same feature across 3 versions of the layer file - current, first attachment, and second attachment:

Current:

```
        {
            "type": "Feature",
            "id": 979,
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -119.27072205704641,
                    50.26543210098277
                ]
            },
            "properties": {
                "FID": 979,
                "Bldng_ID": "B0067525",
                "Bldng_Type": "Office",
                "Address": "3201 30th St.",
                "City": "VERNON"
            }
        },
```

First attachment:

```
        {
            "type": "Feature",
            "id": 979,
            "geometry": {
                "type": "Point",
                "coordinates": [
                    10.496680976289595,
                    3.7760741265765514
                ]
            },
            "properties": {
                "FID": 979,
                "Bldg_ID": "B0014639",
                "Bldg_Type": "Office",
                "Address": "238 Government St",
                "City": "DUNCAN"
            }
        },
```

Second attachment:

```
        {
            "type": "Feature",
            "id": 979,
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -123.71086059960466,
                    48.777545629149962
                ]
            },
            "properties": {
                "FID": 979,
                "Building_N": "B0014639",
                "Address": "238 Government St",
                "City": "DUNCAN",
                "Postal_Cod": "V9L1A5",
                "Region": "Vancouver Island",
                "Descriptio": "Round Bldg",
                "Tenure": "Leased",
                "Facility_T": "Courts",
                "Primary_Us": "Office",
                "Electoral_": "Cowichan-Ladysmith",
                "Complex_Nu": " ",
                "Land_Numbe": " ",
                "Usable_Are": 491.30000000000001,
                "Total_Rent": 717.10000000000002,
                "Parking_St": 13,
                "R_U_Ratio": 1.0415395787899999,
                "Strategic_": " ",
                "Constructi": " ",
                "In_Service": 775699200000,
                "Year_Built": 0,
                "Latitude": 48.777545629999999,
                "Longitude": -123.7108606,
                "lastupdate": "2023-03-29"
            }
        },
```
And I just now noticed that the features aren't the same as I initially thought, though they all have the same FID: the current layer has this in Vernon, while the next 2 layer version have this in Duncan.

We're currently displaying the attributes Building ID, Building Type, Address and City. For the second attachment, I we can use "Building_N" for Building ID. "Facility_T" seems like it might be the best match for Building Type, but it looks like the values for this field are empty for all features.

Is the second attachment one we want to move ahead with, or does it need further changes? 

If it's helpful, I can deploy the second attachment to the development environment so you can inspect them.

Cheers

**Comment by bethbyoung** [comment]
Hi Michael,

Sorry, I forgot to adjust the attribute headings, thanks for the heads-up. I will send the revised geojson in a sec. Sorry about that.

**Comment by bethbyoung** [comment]
It looks good to me, thanks. On another note, I saw that the route line doesn’t change to a lighter colour after the range limit is exceeded. Is that going to be added in again?

**Comment by bethbyoung** [comment]
Sounds good, thanks for the explanation.

**Comment by michaelpnelson** [comment]
@bethbyoung , I also noticed an inconsistency ... the attribute we use for the feature title is different between the EVCS and RPD Building layers - we use Building ID for RPD and Stall Type for EVCS. I think we should update configuration so that Building ID is used for EVCS as well. What do you think? If you agree I'll create an issue to implement this change.

<img width="296" alt="Screenshot 2023-03-31 at 11 43 09 AM" src="https://user-images.githubusercontent.com/1911540/229204329-268e4b90-69a4-4660-b458-d078e3b944e6.png">

**Comment by bethbyoung** [comment]
After you have added in the new attributes for Network, Number and Charger ID, based on the email from yesterday, we can update it to the Charger ID.

**Comment by michaelpnelson** [comment]
@bethbyoung , thanks for clarifying - I missed that part :) . I'll work on an update to include Network, Number and Charger ID this afternoon.

**Comment by michaelpnelson** [comment]
@bethbyoung , the attributes in the EVCS layer have been updated and pushed to dev and prod.

Cheers
