### ISSUE TITLE
CleanBC: Investigate PlugShare and API

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-clean-bc#45]
> [Open in MURAL](https://app.mural.co/t/datasystemsandservices8142/m/datasystemsandservices8142/1674081183025?wid=9-1674081665401) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CleanBC JIRA to GH Integration - CITZ – BCDS – Data Systems and Services

**Comment by NicoledeGreef** [comment]
PO for APS indicated:


![Image](https://user-images.githubusercontent.com/26335003/214489349-91c8ea38-3214-43b4-9243-572ecf6af3ad.png)

I understand this to mean that the API Gateway will give us an endpoint to access from the app and handling the exchange of credentials with the API from Flo EV (e.g. providing the token).  DevOps reps should touch base with APS reps if they are not familiar with their offering.

**Comment by michaelpnelson** [comment]
Copied from our JIRA issue:

# Outcome
PlugShare’s API doesn’t appear to give driving directions to a charging location, but it does have lots to offer in finding charging locations and providing data about them.

An API key is required. A key can be requested at [API Request Form](https://developer.plugshare.com/access) . However this page currently says that only commercial licenses (i.e. not private or non-commercial) are available at this time. We would expect Clean BC to get and maintain an API key.

Key entities in their API (https://developer.plugshare.com/docs ) are Location, Station, and Outlet. A Location contains one or more Stations, and a Station contains one or more Outlets.

API for Location (https://developer.plugshare.com/docs/#location ) seems to be most useful to us. It has methods to:

- Get Locations nearby (via lat/long or address)
- Get Locations in a region via lat/long spans
- Search Locations using a query, which can include the name of a city or state/province and several other attributes
- Fetch Locations along a route, via a route (polyline of lat/longs) plus a distance in meters from the route
