### ISSUE TITLE
Legend changes

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-clean-bc#86]
Lindsay and Beth to work with Andrew to specify the wording for the layer legend.  Criteria to be added in this ticket.

**Comment by NicoledeGreef** [comment]
MVP

Business will supply the text values for the highlighted values:

![Image](https://user-images.githubusercontent.com/26335003/220761678-b45f2667-c888-4e9f-a01b-c6f8f659b8fa.png)

**Comment by michaelpnelson** [comment]
I'm going to move this forward as the legend is much improved now due to changes for https://github.com/bcgov/smk-clean-bc/issues/92 as well as earlier changes.
