### ISSUE TITLE
Colour (symbolization) finalization

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-clean-bc#90]
As agreed at the Feb 15/23 check-in meeting, the purpose of this ticket is to list the symbolization aspects of the application that can/perhaps should be modified.

Items:

Layers (symbology and colour)
-add list of layers here

Highlighted route line (colour); marker for end of range; how should the in range line look versus the beyond range line?

Others?

**Comment by bethbyoung** [comment]
Symbolization:

Public EV stations:
- change colour from red to orange
- different colour (e.g., Hex #00ffff or #ffff00) around any stations that have a value in the EV DC Fast Count field 

Ministry EV Stations:
- need both Fleet and EmVi station symbology to show up in legend, I can provide a GeoJSON file for each if that is easier
- add white border around symbols, same as public EV station symbology

RPD Buildings:
- add white border around symbols, same as public EV station symbology

**Comment by NicoledeGreef** [comment]
"different colour (e.g., Hex #00ffff or #ffff00) around any stations that have a value in the EV DC Fast Count field" highlights locations that are Fast chargers
